/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MembersRouteImport } from './routes/members'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsClubRouteImport } from './routes/settings.club'
import { Route as MembersMemberIdRouteImport } from './routes/members_.$memberId'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsClubRoute = SettingsClubRouteImport.update({
  id: '/settings/club',
  path: '/settings/club',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersMemberIdRoute = MembersMemberIdRouteImport.update({
  id: '/members_/$memberId',
  path: '/members/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/invite/$token': typeof InviteTokenRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/settings/club': typeof SettingsClubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/invite/$token': typeof InviteTokenRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/settings/club': typeof SettingsClubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/invite/$token': typeof InviteTokenRoute
  '/members_/$memberId': typeof MembersMemberIdRoute
  '/settings/club': typeof SettingsClubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/members'
    | '/onboarding'
    | '/profile'
    | '/invite/$token'
    | '/members/$memberId'
    | '/settings/club'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/members'
    | '/onboarding'
    | '/profile'
    | '/invite/$token'
    | '/members/$memberId'
    | '/settings/club'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/members'
    | '/onboarding'
    | '/profile'
    | '/invite/$token'
    | '/members_/$memberId'
    | '/settings/club'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MembersRoute: typeof MembersRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  InviteTokenRoute: typeof InviteTokenRoute
  MembersMemberIdRoute: typeof MembersMemberIdRoute
  SettingsClubRoute: typeof SettingsClubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/club': {
      id: '/settings/club'
      path: '/settings/club'
      fullPath: '/settings/club'
      preLoaderRoute: typeof SettingsClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members_/$memberId': {
      id: '/members_/$memberId'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof MembersMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MembersRoute: MembersRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  InviteTokenRoute: InviteTokenRoute,
  MembersMemberIdRoute: MembersMemberIdRoute,
  SettingsClubRoute: SettingsClubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
