/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MembersRouteImport } from './routes/members'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsTeamRouteImport } from './routes/settings.team'
import { Route as SettingsClubRouteImport } from './routes/settings.club'
import { Route as MembersMemberIdRouteImport } from './routes/members_.$memberId'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ActivitiesActivityIdRouteImport } from './routes/activities_.$activityId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTeamRoute = SettingsTeamRouteImport.update({
  id: '/settings/team',
  path: '/settings/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsClubRoute = SettingsClubRouteImport.update({
  id: '/settings/club',
  path: '/settings/club',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersMemberIdRoute = MembersMemberIdRouteImport.update({
  id: '/members_/$memberId',
  path: '/members/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesActivityIdRoute = ActivitiesActivityIdRouteImport.update({
  id: '/activities_/$activityId',
  path: '/activities/$activityId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/activities/$activityId': typeof ActivitiesActivityIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/settings/club': typeof SettingsClubRoute
  '/settings/team': typeof SettingsTeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/activities/$activityId': typeof ActivitiesActivityIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/settings/club': typeof SettingsClubRoute
  '/settings/team': typeof SettingsTeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/activities_/$activityId': typeof ActivitiesActivityIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/members_/$memberId': typeof MembersMemberIdRoute
  '/settings/club': typeof SettingsClubRoute
  '/settings/team': typeof SettingsTeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/groups'
    | '/login'
    | '/members'
    | '/onboarding'
    | '/profile'
    | '/activities/$activityId'
    | '/invite/$token'
    | '/members/$memberId'
    | '/settings/club'
    | '/settings/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/groups'
    | '/login'
    | '/members'
    | '/onboarding'
    | '/profile'
    | '/activities/$activityId'
    | '/invite/$token'
    | '/members/$memberId'
    | '/settings/club'
    | '/settings/team'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/groups'
    | '/login'
    | '/members'
    | '/onboarding'
    | '/profile'
    | '/activities_/$activityId'
    | '/invite/$token'
    | '/members_/$memberId'
    | '/settings/club'
    | '/settings/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  GroupsRoute: typeof GroupsRoute
  LoginRoute: typeof LoginRoute
  MembersRoute: typeof MembersRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  ActivitiesActivityIdRoute: typeof ActivitiesActivityIdRoute
  InviteTokenRoute: typeof InviteTokenRoute
  MembersMemberIdRoute: typeof MembersMemberIdRoute
  SettingsClubRoute: typeof SettingsClubRoute
  SettingsTeamRoute: typeof SettingsTeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/team': {
      id: '/settings/team'
      path: '/settings/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof SettingsTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/club': {
      id: '/settings/club'
      path: '/settings/club'
      fullPath: '/settings/club'
      preLoaderRoute: typeof SettingsClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members_/$memberId': {
      id: '/members_/$memberId'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof MembersMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities_/$activityId': {
      id: '/activities_/$activityId'
      path: '/activities/$activityId'
      fullPath: '/activities/$activityId'
      preLoaderRoute: typeof ActivitiesActivityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  GroupsRoute: GroupsRoute,
  LoginRoute: LoginRoute,
  MembersRoute: MembersRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  ActivitiesActivityIdRoute: ActivitiesActivityIdRoute,
  InviteTokenRoute: InviteTokenRoute,
  MembersMemberIdRoute: MembersMemberIdRoute,
  SettingsClubRoute: SettingsClubRoute,
  SettingsTeamRoute: SettingsTeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
